import { Check, ChevronDown, Search } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useBridgeTheme } from "../lib/theme";
export type PickerOption = { value: string; label: string; detail?: string };
export function SearchSelect({ value, onChange, options, placeholder = "Select an option", searchable = true, className = "", tone = "auto" }: { value: string; onChange: (value: string) => void; options: PickerOption[]; placeholder?: string; searchable?: boolean; className?: string; tone?: "auto" | "dark" }) {
  const { theme } = useBridgeTheme();
  const dark = tone === "dark" || theme === "dark";
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const root = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const selected = options.find((option) => option.value === value); const filtered = options.filter((option) => option.label.toLowerCase().includes(query.toLowerCase()));
  return <div ref={root} className={`relative ${className}`}><button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(!open)} className={`flex w-full items-center justify-between rounded-xl border px-4 py-3 text-left text-sm hover:border-[#2e8b72]/60 ${dark ? "border-white/15 bg-white/5 text-white" : "border-[#171714]/15 bg-white text-[#171714]"}`}><span className={selected ? (dark ? "text-white" : "text-[#171714]") : (dark ? "text-white/65" : "text-[#171714]/65")}>{selected?.label || placeholder}</span><ChevronDown className={`h-4 w-4 ${dark ? "text-[#d6ff57]" : "text-[#206653]"} transition-transform ${open ? "rotate-180" : ""}`} /></button>{open && <div className={`absolute z-50 mt-2 max-h-64 w-full overflow-hidden rounded-xl border p-2 shadow-2xl ${dark ? "border-white/15 bg-[#1b1b18] text-white" : "border-[#171714]/15 bg-white text-[#171714]"}`}>{searchable && <label className={`mb-2 flex items-center gap-2 rounded-lg px-3 py-2 ${dark ? "bg-white/5" : "bg-[#171714]/5"}`}><Search className={`h-4 w-4 ${dark ? "text-white/60" : "text-[#171714]/60"}`} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} className={`min-w-0 flex-1 bg-transparent text-sm outline-none ${dark ? "text-white placeholder:text-white/60" : "text-[#171714] placeholder:text-[#171714]/60"}`} placeholder="Search…" /></label>}<div className="max-h-48 overflow-y-auto scrollbar-hide" role="listbox">{filtered.map((option) => <button key={option.value} type="button" role="option" aria-selected={value === option.value} onClick={() => { onChange(option.value); setOpen(false); setQuery(""); }} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm ${dark ? "text-white/85 hover:bg-white/10 hover:text-white" : "text-[#171714]/85 hover:bg-[#171714]/5 hover:text-[#171714]"}`}><span><span className="block">{option.label}</span>{option.detail && <span className={`block text-xs ${dark ? "text-white/60" : "text-[#171714]/60"}`}>{option.detail}</span>}</span>{value === option.value && <Check className={`h-4 w-4 ${dark ? "text-[#d6ff57]" : "text-[#206653]"}`} />}</button>)}{filtered.length === 0 && <p className={`px-3 py-4 text-sm ${dark ? "text-white/65" : "text-[#171714]/65"}`}>No matches found.</p>}</div></div>}</div>;
}
