import { Link, useLocation } from "react-router-dom";
import { BrandLink } from "../components/BrandLink";

type Section = { title: string; body: string };
const policies: Record<string, { title: string; intro: string; sections: Section[] }> = {
  "/terms": { title: "Terms of Service", intro: "These Terms govern use of BRIDGE Everything Limited's marketplace, vendor stores, and protected-payment features by Customers, Vendors and Users.", sections: [
    { title: "About BRIDGE", body: "BRIDGE is a technology-enabled marketplace connecting Customers with independent Vendors. Unless expressly stated, BRIDGE is not the manufacturer, seller, supplier or ultimate provider of the Goods or Services listed." },
    { title: "Accounts & eligibility", body: "You must have the legal capacity required by law, provide accurate account information, keep your credentials secure, and not impersonate, sell, rent or fraudulently use an Account. BRIDGE may require verification and may suspend Accounts for breach, fraud or security reasons." },
    { title: "Vendor responsibilities", body: "Vendors warrant that listings are truthful, Goods are genuine and lawfully sourced, they hold any required licences, and they will honour accepted Orders, maintain an eligible payout account, and provide genuine delivery evidence. Off-platform deals to evade fees or bypass protections are prohibited." },
    { title: "Orders & pricing", body: "Submitting an Order is an offer to purchase; acceptance happens only when confirmed through the Platform. Checkout may include the price, taxes, delivery, platform and payment charges. BRIDGE or the Vendor may cancel unaccepted Orders for unavailability, pricing errors, fraud or other lawful reasons." },
    { title: "Payments, commissions & settlement", body: "Payments may be processed by BRIDGE or authorised third-party payment providers. BRIDGE may charge transaction commissions, subscription, advertising and delivery-related fees as disclosed in a Vendor's commercial terms. Settlement may be delayed for fraud, chargeback, dispute or regulatory reasons." },
    { title: "Delivery", body: "Delivery may be performed by Vendors, BRIDGE or third-party logistics providers. Vendors remain responsible for correct preparation unless otherwise agreed, and delivery estimates are not guarantees unless expressly stated." },
    { title: "Consumer rights, refunds & disputes", body: "A separate Refund and Cancellation Policy applies. Remedies may include cancellation, refund, replacement, repair or credit. Users should first contact BRIDGE customer support; disputes with Nigerian Users are governed by Nigerian law and, subject to mandatory rights, submitted to competent Nigerian courts." },
    { title: "Reviews & content", body: "Reviews must reflect genuine experiences — fake or paid reviews, threats and false allegations are prohibited. Users retain ownership of their Content but grant BRIDGE a licence to host, display and use it to operate and promote the Platform." },
    { title: "Prohibited use & goods", body: "Fraud, money laundering, counterfeit or stolen goods, illegal drugs, unlicensed medicines, weapons, unlawful adult services and similar categories are prohibited. BRIDGE may edit, suspend or remove listings, Accounts or Vendor Stores that breach these rules." },
    { title: "Liability & indemnity", body: "To the fullest extent permitted by law, BRIDGE's aggregate liability for a Transaction is capped at the amount the affected Customer paid BRIDGE for that Transaction, and BRIDGE is not liable for losses arising solely from independent Vendor acts or third-party failures. Vendors indemnify BRIDGE against claims arising from their Goods, Services or breach. Nothing here removes a right that cannot lawfully be excluded." },
    { title: "Suspension & termination", body: "BRIDGE may suspend or terminate Accounts or Vendor Stores for fraud, breach, unsafe or counterfeit products, expired licences, or other legitimate risk reasons. Users may close their Account subject to unresolved Transactions and obligations." },
    { title: "Governing law & contact", body: "These Terms are governed by Nigerian law, subject to mandatory consumer rights. Legal notices, customer support and vendor support: BRIDGE Everything Limited, 2 Ikot Udoma Estate Road, Eket · bridgeverything@gmail.com · +234 905 836 0929." },
  ] },
  "/privacy": { title: "Privacy Policy", intro: "This Policy explains how BRIDGE Everything Limited collects, uses, discloses and protects personal data across the marketplace, vendor stores, payments and support channels, under the Nigeria Data Protection Act 2023 and applicable law.", sections: [
    { title: "Information we collect", body: "Identity and profile data, contact and account details, order and transaction history, vendor registration and verification information, limited payment information from payment providers, device and diagnostic data, reviews and messages, and location/delivery information. Payment-card secrets such as PINs or CVVs are not ordinarily retained." },
    { title: "How we use information", body: "To operate accounts and the marketplace, facilitate orders, deliveries, payments and refunds, verify Vendors, prevent fraud and abuse, provide support, personalise search, improve the Service, send lawful marketing, and meet legal, tax and regulatory obligations." },
    { title: "Sharing between marketplace parties", body: "Limited information is shared between BRIDGE, Customers and Vendors where reasonably necessary — for example, a Vendor may need a Customer's name, delivery address and order details to fulfil an Order. Vendors that independently determine their own processing purposes may have separate controller obligations." },
    { title: "Payments & settlement", body: "Payments and settlement may be facilitated through licensed or otherwise lawfully authorised payment providers and banks. BRIDGE will not represent itself as a bank or payment service provider unless separately authorised, and retains financial records for accounting, audit and fraud-prevention purposes." },
    { title: "Cookies & marketing", body: "BRIDGE may use cookies, SDKs, pixels and similar technologies for necessary functions, analytics, security and, where lawful, advertising, with appropriate consent choices where required. Marketing messages include an opt-out; this does not stop essential service communications." },
    { title: "Disclosure of personal data", body: "Data may be disclosed, where lawful and necessary, to transaction counterparties, delivery and logistics partners, payment processors, verification and fraud-prevention providers, professional advisers, and regulators, courts or law enforcement. BRIDGE does not sell personal data as a commercial commodity." },
    { title: "International transfers & retention", body: "Personal data may be transferred to or accessed from outside Nigeria using legally required safeguards. Data is retained only as long as reasonably necessary for the purpose collected, contractual, legal or fraud-prevention needs, then deleted, anonymised or securely disposed of." },
    { title: "Security & data breaches", body: "BRIDGE maintains technical and organisational measures appropriate to risk, including access controls and encryption where appropriate. Suspected breaches are investigated and, where required by law, notified to the regulator and affected individuals. Report incidents to bridgeverything@gmail.com." },
    { title: "Your rights", body: "Subject to applicable law, you may have rights to access, correct, object to, restrict, delete or port your personal data, and to withdraw consent or complain to a supervisory authority. Send requests to bridgeverything@gmail.com; BRIDGE may request identity verification first." },
    { title: "Automated decisions & AI", body: "BRIDGE may use automated tools for recommendations, ranking, fraud detection and personalisation. Where automated decisions have legal or similarly significant effects, required notice and human-review safeguards apply. Personal data is not used to train third-party general-purpose AI systems contrary to law or disclosed practice." },
    { title: "Children & minors", body: "BRIDGE does not intentionally collect children's personal data except where permitted by law and with required parental or guardian involvement. Concerns can be raised at bridgeverything@gmail.com." },
    { title: "Contact & complaints", body: "BRIDGE Everything Limited, 2 Ikot Udoma Estate Road, Eket · bridgeverything@gmail.com · +234 905 836 0929. Complaints should include \"PRIVACY COMPLAINT\" in the subject line; you may also have a right to complain to the Nigeria Data Protection Commission." },
  ] },
  "/buyer-protection": { title: "Buyer Protection & Disputes", intro: "BRIDGE protects only payments made through an accepted BRIDGE order.", sections: [
    { title: "How it works", body: "The buyer sees the seller price, BRIDGE protection fee, and processing charge before payment. Seller earnings become available after the buyer confirms delivery." },
    { title: "Report a problem", body: "Before confirming delivery, use “Report issue” in the protected order and provide a clear explanation. This places the order under review and blocks seller release." },
    { title: "Refunds", body: "Where BRIDGE approves a refund, it is initiated back through the payment provider. Processing times can depend on the payment method and provider." },
    { title: "Not covered", body: "Cash payments, direct transfers, informal agreements, and payments outside BRIDGE are not covered by BRIDGE buyer protection." },
  ] },
};

export function Legal() {
  const policy = policies[useLocation().pathname] || policies["/terms"];
  return <main className="min-h-screen bg-[#f4ede2] text-ink font-body"><nav className="border-b border-ink/10 px-6 py-5"><BrandLink /></nav><article className="max-w-3xl mx-auto px-6 py-12 sm:py-20"><p className="text-xs uppercase tracking-[0.2em] text-[#2E8B72] font-semibold">Legal · Draft for review</p><h1 className="font-display text-4xl sm:text-6xl font-semibold tracking-tight mt-4">{policy.title}.</h1><p className="text-ink/55 mt-5 text-lg leading-relaxed">{policy.intro}</p><p className="mt-5 rounded-xl bg-[#dce9df]/10 border border-[#2E8B72]/15 p-4 text-sm text-ink/70">Effective: 8 September 2026. This summary must be reviewed and approved by BRIDGE's Nigerian legal and compliance advisers before public launch; the full Terms & Conditions and Privacy Policy documents govern.</p><div className="mt-10 space-y-9">{policy.sections.map((section) => <section key={section.title}><h2 className="font-display text-2xl font-semibold">{section.title}</h2><p className="mt-3 text-ink/60 leading-relaxed">{section.body}</p></section>)}</div><div className="mt-12 pt-6 border-t border-ink/10 flex flex-wrap gap-4 text-sm text-[#2E8B72]"><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link><Link to="/buyer-protection">Buyer Protection</Link></div></article></main>;
}