import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { OrderCards } from "../components/OrderCards";
import type { MarketplaceOrder } from "../components/OrderCards";
import { apiFetch } from "../lib/api";

export function Orders() {
  const [orders, setOrders] = useState<MarketplaceOrder[] | undefined>(undefined); const [searchParams, setSearchParams] = useSearchParams(); const [paidOrderId, setPaidOrderId] = useState(""); const [contact, setContact] = useState({ name: "", phone: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => apiFetch("/orders/mine").then((data) => setOrders(data.orders)).catch(() => setOrders([]));
  useEffect(() => { load(); const reference = searchParams.get("reference"); if (reference) apiFetch(`/payments/paystack/verify/${reference}`).then((data) => { if (data.order?.id) setPaidOrderId(data.order.id); setSearchParams({}); load(); }).catch((err) => setError(err.message)); }, []);
  async function submitContact(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await apiFetch(`/orders/${paidOrderId}/contact`, { method: "POST", body: JSON.stringify(contact) }); setPaidOrderId(""); load(); } catch (err: any) { setError(err.message); } finally { setSaving(false); } }
  return <div className="min-h-screen bg-paper text-ink font-body"><nav className="flex items-center gap-4 px-6 md:px-12 py-5 max-w-4xl mx-auto border-b border-ink/10"><Link to="/messages" className="text-ink/50 hover:text-ink"><ArrowLeft className="w-5 h-5" /></Link><Link to="/" className="font-display font-semibold">BRIDGE</Link></nav><main className="max-w-4xl mx-auto px-6 md:px-12 py-10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-signal mb-3">Transactions</p><h1 className="font-display text-4xl font-semibold tracking-tight">My orders.</h1>{paidOrderId && <form onSubmit={submitContact} className="mt-6 rounded-2xl bg-white border border-signal/30 p-5"><h2 className="font-display text-xl font-semibold">Payment confirmed — delivery contact</h2><p className="text-sm text-ink/45 mt-1">Share this only now, so the vendor can fulfil your paid order.</p><div className="grid sm:grid-cols-2 gap-3 mt-4"><input required className="input-field" placeholder="Recipient name" value={contact.name} onChange={(e) => setContact({ ...contact, name: e.target.value })} /><input required className="input-field" inputMode="tel" placeholder="Phone number" value={contact.phone} onChange={(e) => setContact({ ...contact, phone: e.target.value })} /></div><button disabled={saving} className="btn-primary px-5 py-3 mt-4 disabled:opacity-50">{saving ? "Saving…" : "Share delivery contact"}</button></form>}{error && <p className="text-sm text-signal mt-4">{error}</p>}<p className="mt-3 text-ink/40 mb-8">Your BRIDGE deal history and protected checkout status.</p>{orders === undefined ? <p className="text-sm text-ink/40">Loading orders...</p> : <OrderCards orders={orders} vendorView={false} />}</main></div>;
}