import { useEffect, useState } from "react";
import { AdminLayout } from "../../components/AdminLayout";
import { apiFetch } from "../../lib/api";
import { AlertTriangle, Loader2, ShieldCheck } from "lucide-react";

type Alert = { id: string; order_id: string; order_title: string; buyer_name: string | null; vendor_name: string; severity: "low" | "medium" | "high" | "critical"; code: string; details: Record<string, unknown>; created_at: string };
const severityStyle = { low: "bg-ink/5 text-ink/60", medium: "bg-gold/15 text-ink", high: "bg-signal/15 text-signal", critical: "bg-signal text-paper" };

export function FraudAlerts() {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [reviewing, setReviewing] = useState<string | null>(null); const [error, setError] = useState("");
  function load() { setLoading(true); apiFetch("/admin/fraud-alerts").then((data) => setAlerts(data.alerts)).catch((err) => setError(err.message)).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, []);
  async function review(id: string, status: "resolved" | "dismissed") { const note = window.prompt(status === "resolved" ? "Explain how this risk was resolved:" : "Explain why this alert is being dismissed:"); if (!note) return; setReviewing(id); setError(""); try { await apiFetch(`/admin/fraud-alerts/${id}`, { method: "PATCH", body: JSON.stringify({ status, note }) }); load(); } catch (err: any) { setError(err.message); } finally { setReviewing(null); } }
  return <AdminLayout><div className="max-w-5xl mx-auto"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-signal mb-3">Trust & safety</p><h1 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight">Fraud review queue.</h1><p className="mt-3 text-ink/45 max-w-2xl">High-risk alerts block seller payout until a reviewer records a decision. Every review is added to the order audit trail.</p></div>{error && <p className="mb-5 text-sm text-signal">{error}</p>}{loading ? <div className="py-20 text-center"><Loader2 className="w-6 h-6 animate-spin mx-auto text-ink/20" /><p className="text-sm text-ink/35 mt-3">Loading alerts…</p></div> : alerts.length === 0 ? <div className="rounded-2xl bg-white border border-ink/10 py-16 text-center"><ShieldCheck className="w-8 h-8 text-signal mx-auto mb-3" /><p className="font-medium">No open fraud alerts.</p><p className="text-sm text-ink/40 mt-1">Orders requiring review will appear here.</p></div> : <div className="space-y-3">{alerts.map((alert) => <article key={alert.id} className="bg-white border border-ink/10 rounded-2xl p-5"><div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><div className="flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-signal" /><h2 className="font-display text-lg font-semibold">{alert.code.replaceAll("_", " ")}</h2><span className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-1 rounded-full ${severityStyle[alert.severity]}`}>{alert.severity}</span></div><p className="mt-2 text-sm text-ink/55">{alert.order_title} · Buyer: {alert.buyer_name || "Unknown"} · Seller: {alert.vendor_name}</p><p className="mt-1 text-xs text-ink/35">Raised {new Date(alert.created_at).toLocaleString()}</p><pre className="mt-3 rounded-lg bg-ink/[0.03] p-3 text-xs text-ink/55 whitespace-pre-wrap font-mono">{JSON.stringify(alert.details, null, 2)}</pre></div><div className="flex sm:flex-col gap-2 shrink-0"><button disabled={reviewing === alert.id} onClick={() => review(alert.id, "resolved")} className="px-3 py-2 text-xs rounded-lg bg-ink text-paper disabled:opacity-50">Resolve</button><button disabled={reviewing === alert.id} onClick={() => review(alert.id, "dismissed")} className="px-3 py-2 text-xs rounded-lg border border-ink/15 disabled:opacity-50">Dismiss</button></div></div></article>)}</div>}</div></AdminLayout>;
}
